# Generated by Django 4.2.6 on 2023-10-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_remove_audiofile_file_path_audiofile_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='audio_channels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='authors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='musical_genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='sample_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='where_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='year_recorded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
