# Generated by Django 4.2.6 on 2023-10-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_metadata_audio_channels_metadata_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='album',
            field=models.CharField(blank=True, default='album', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='artist',
            field=models.CharField(blank=True, default='artist', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='audio_channels',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='authors',
            field=models.CharField(blank=True, default='authors', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='comment',
            field=models.TextField(blank=True, default='comment', null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='custom_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='duration',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='genre',
            field=models.CharField(blank=True, default='genre', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='musical_genre',
            field=models.CharField(blank=True, default='musical_genre', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='sample_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='track_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='where_from',
            field=models.CharField(blank=True, default='where_from', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='year_recorded',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
